### ISSUE TITLE
Remove awscli from dependencies

### ISSUE THREAD

**Issue by charsleysa** [localstack/awscli-local#20]
Starting with AWS CLI v2, the tool is no longer distributed as a pip package but instead a standalone tool with all dependencies included.

Due to awscli-local making the awscli a requirement, the v2 CLI gets overwritten by the v1 CLI (as they both get installed to `/usr/local/bin/aws`).

It would be better to have developers manually install the version of the AWS CLI they would like to use instead of awscli-local trying to install it for them.

**Comment by rest-radwtr** [comment]
It seems that `awslocal` will always use the v1 CLI even if the v2 CLI is listed first on the user's `PATH`. This can lead to confusing differences in behaviour when performing local vs. remote operations.

```
$ aws --version
aws-cli/2.0.14 Python/3.7.3 Linux/4.4.0-18362-Microsoft botocore/2.0.0dev18
$ awslocal --version
aws-cli/1.18.63 Python/3.7.5 Linux/4.4.0-18362-Microsoft botocore/1.16.13
```

For example, we're still hitting [this v1 "feature"](https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-paramfile) when using `awslocal` even though it is fixed in all our other scripts that use the v2 CLI.

**Comment by pinzon** [comment]
Now there is a way to install awscli-local without installing the awscli package. Please check the PR #30
